Repository Secret-Hitler-Dev/secret_hitler, pull requests merged in 2020-05, with the labels that each got.

#59 Fixed room code bug on dashboard
  .gitignore
  services/application/public/index.html
  services/application/src/components/Dashboard/Dashboard.js
Labels: bug, frontend

#60 updated readme
  README.md
  services/.env.template
  services/package.json
Labels: documentation

#53 Game dashboard: control bar complete
  services/application/media/game_assets/board_fas.png
  services/application/media/game_assets/board_lib.png
  services/application/media/game_assets/card_fas.png
  services/application/media/game_assets/card_lib.png
  services/application/media/game_assets/card_lib_win.png
  services/application/media/game_assets/index.js
  services/application/media/game_assets/ja.png
  services/application/media/game_assets/mem_fas.png
  services/application/media/game_assets/mem_lib.png
  services/application/media/game_assets/nein.png
  services/application/media/game_assets/policy.png
  services/application/media/game_assets/policy_fas.png
  services/application/media/game_assets/policy_lib.png
  services/application/media/game_assets/role_fas.png
  services/application/media/game_assets/role_hitler.png
  services/application/media/game_assets/role_lib.png
  services/application/src/components/GameBoard/GameBoard.js
  services/application/src/components/GameCard/GameCard.js
  services/application/src/components/GameDash/GameDash.css
  services/application/src/components/GameDash/GameDash.js
  services/application/src/components/GameEnvelope/GameEnvelope.js
  services/application/src/pages/Game/Game.js
  services/application/src/style/index.css
Labels: frontend

#65 Duplicate functions: getAll(...), collectStats(...)
  services/apis/users.js
Labels: bug, priority 1

#67 Backend / Frontend Test frameworks
  README.md
  services/.babelrc
  services/__mocks__/fileMock.js
  services/apis/users.js
  services/application/public/index.html
  services/application/src/SetupTests.js
  services/application/src/components/App/App.test.js
  services/jest.config.js
  services/package-lock.json
  services/package.json
  services/server.js
  services/tests/controllers/db-handler.js
  services/tests/data/UsersData.js
  services/tests/users.js
  services/webpack.config.js
Labels: backend, frontend, priority 1

#103 workflow: Adding linting for Pull Request titles
  .github/workflows/prlint.yml
Labels: workflow

#107 backend: Join and create game works now
  services/apis/game.js
  services/apis/users.js
  services/application/src/components/App/App.js
  services/application/src/components/Dashboard/Dashboard.js
  services/application/src/components/GameDash/GameDash.js
  services/application/src/pages/Game/Game.js
  services/application/src/pages/Guest/Guest.js
  services/application/src/pages/Login/Login.js
  services/application/src/pages/Register/Register.js
  services/models/Player.js
  services/models/User.js
  services/server-utils.js
  services/server.js
  services/tests/data/UsersData.js
  services/tests/users.js
Labels: backend

#108 frontend: Added the game log to the game dash
  services/application/src/components/GameBoard/GameBoard.js
  services/application/src/components/GameCard/GameCard.js
  services/application/src/components/GameDash/GameDash.js
  services/application/src/style/index.css
  services/package-lock.json
  services/package.json
Labels: frontend

#79 frontend: Completed game lobby.
  services/application/src/components/GameBoard/GameBoard.js
  services/application/src/components/GameDash/GameDash.css
  services/application/src/components/GameDash/GameDash.js
  services/application/src/components/GameEnvelope/GameEnvelope.css
  services/application/src/components/GameEnvelope/GameEnvelope.js
  services/application/src/pages/Game/Game.js
  services/application/src/style/index.css
  services/package-lock.json
  services/package.json
Labels: frontend

#111 backend: Bug Fix
  services/apis/game.js
Labels: backend

#112 fix: sockets now work when running on dev server
  services/webpack.config.js
Labels: bug
